"""核心基础设施模块"""

from .message_bus import MessageBroker, Topic
from .topic_defs import (
    # 仿真话题
    SIMU_IMAGES, SIMU_JOINTS, SIMU_GRIPPER, SIMU_TCP_POSE,
    SIMU_OBJECT_POS, SIMU_STATUS, SIMU_CARTESIAN,
    ALL_SIMU_TOPICS,
    # 真实机器人话题
    REAL_IMAGES, REAL_JOINTS, REAL_CARTESIAN, REAL_GRIPPER, REAL_STATUS,
    ALL_REAL_TOPICS,
    # 数据采集话题
    COLLECT_STATUS, COLLECT_TASK, COLLECT_LOG, COLLECT_EPISODE,
    ALL_COLLECT_TOPICS,
)

__all__ = [
    'MessageBroker',
    'Topic',
    'SIMU_IMAGES', 'SIMU_JOINTS', 'SIMU_GRIPPER', 'SIMU_TCP_POSE',
    'SIMU_OBJECT_POS', 'SIMU_STATUS', 'SIMU_CARTESIAN', 'ALL_SIMU_TOPICS',
    'REAL_IMAGES', 'REAL_JOINTS', 'REAL_CARTESIAN', 'REAL_GRIPPER', 'REAL_STATUS',
    'ALL_REAL_TOPICS',
    'COLLECT_STATUS', 'COLLECT_TASK', 'COLLECT_LOG', 'COLLECT_EPISODE',
    'ALL_COLLECT_TOPICS',
]
